- hosts: localhost
  gather_facts: yes
  become: yes
  vars_files:
    - keys.yml

  tasks:
    - name: Gather Snapshot Facts
      ec2_snapshot_facts:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"

    - name: Create Volume Snapshot
      ec2_snapshot:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        instance_id: i-0ecb92b87b93110cc
        device_name: /dev/sdf
        state: present
        description: "On Demand Volume Backup"
