- hosts: localhost
  gather_facts: yes
  become: yes
  vars_files:
    - keys.yml
  tasks:
    - name: Change instances state by tag
      ec2_facts:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        state: running
        wait: yes
        instance_tags:
          Name: Demo
        register: ec2
    - name: Output IP Addresses of instances
      ec2_eip:
        debug:
          msg: "IP address is {{ eip.public_ip }}"
        loop: "{{ ec2.instances }}"
