- hosts: localhost
  gather_facts: yes
  become: yes
  vars_files:
    - keys.yml
  tasks:
    - name: remove tags
      ec2_tag:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        resource: Demo
        tags:
          Name: ''
        state: absent
        purge_tags: true
