- hosts: localhost
  gather_facts: yes
  become: yes
  vars_files:
    - keys.yml

  tasks:
    - name: Get VPC Facts
      ec2_vpc_net_info:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
      register: vpc_facts
    - debug:
        var: vpc_facts

